# Testweise: AND OR XOR
./runTwoCardBOOLEAN.sh AND 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1'
./runTwoCardBOOLEAN.sh AND 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_LV_AND=1'
./runTwoCardBOOLEAN.sh OR 4 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_LV_OR=1'
./runTwoCardBOOLEAN.sh OR 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_LV_AND=1'
./runTwoCardBOOLEAN.sh XOR 4 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_XOR=1'
./runTwoCardBOOLEAN.sh COPY 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_COPY=1'


# COPY
## there is a protocol for 6 Cards and 2 Operations -> find that without Modules
## try to find a protocol with 5 Cards 
./runTwoCardBOOLEAN.sh COPY 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 5 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardBOOLEAN.sh COPY 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=2 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=2 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=2 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=2 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 5 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=2 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'


./runTwoCardBOOLEAN.sh COPY 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=4 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=4 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=4 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=4 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardBOOLEAN.sh COPY 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'


./runTwoCardBOOLEAN.sh COPY 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 6 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardBOOLEAN.sh COPY 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 6 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardBOOLEAN.sh COPY 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardBOOLEAN.sh COPY 6 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'


# Half Adder







