# 4 cards

./runTwoCardsADDER.sh 4 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 5 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardsADDER.sh 4 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 4 5 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'


#5 cards
./runTwoCardsADDER.sh 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardsADDER.sh 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardsADDER.sh 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardsADDER.sh 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=4 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardADDER.sh 5 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 5 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 5 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 5 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=8 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

#6 cards 
./runTwoCardADDER.sh 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 6 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 6 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 6 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardADDER.sh 6 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 6 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 6 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 6 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

#7 cards
./runTwoCardADDER.sh 7 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 7 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 7 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 7 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardADDER.sh 7 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 7 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 7 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 7 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

#8 cards
./runTwoCardADDER.sh 8 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 8 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 8 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 8 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=1 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'

./runTwoCardADDER.sh 8 1 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 8 2 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 8 3 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
./runTwoCardADDER.sh 8 4 '-D WEAK_SECURITY=2 -D CLOSED_PROTOCOL=1 -D MAX_PERM_SET_SIZE=2 -D USE_FR_AND=1 -D USE_FR_XOR=1 -D USE_LV_AND=1 -D USE_LV_OR=1 -D USE_FR_COPY=1'
